### ISSUE TITLE
missing tests for configurations

### ISSUE THREAD

**Issue by matthiashermsen** [rettich-team/server#2]
- [x] [Base Config Service](https://github.com/rettich-team/server/blob/master/src/configurations/base.configuration.service.spec.ts)

- [x] [Database Config Service](https://github.com/rettich-team/server/blob/master/src/configurations/database.configuration.service.spec.ts)

- [x] [Environment Config Service](https://github.com/rettich-team/server/blob/master/src/configurations/environment.configuration.service.spec.ts)

- [x] [Server Config Service](https://github.com/rettich-team/server/blob/master/src/configurations/server.configuration.service.spec.ts)

- [x] [Swagger Config Service](https://github.com/rettich-team/server/blob/master/src/configurations/swagger.configuration.service.spec.ts)

- [x] [Location Config Service](https://github.com/rettich-team/server/blob/master/src/configurations/location.configuration.service.spec.ts)

**Comment by bastipnt** [comment]
was genau soll hier getestet werden? einfach nur, dass die config funktioniert? weil logik ist hier ja nicht drin. eigentlich macht typescript hier ja schon alles für uns. wenn etwas in den env variablen fehlt dann gibts nen fehler

**Comment by matthiashermsen** [comment]
Da bin ich mir selbst noch nicht ganz sicher, ich habe es nur mal aufgenommen. Also den Base Service brauchen wir nicht testen, da ist keine Methode public. Aber man könnte bei den Klassen, die von diesem erben, testen, ob beispielsweise der Wert korrekt validiert und umgewandelt wird.
